import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Link from "next/link";

//Note#8: This is the traditional way of  importing a file using relative path import, but it be am headache if we have complex nested folder heirarcy
// import Header from "../components/header";
// Instead Next Js gives us a shortcut to import using Absolute path using a symbol "@". this @ will directly goes to src folder , and from their we can navigate to any folder we want
import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Note#5: this is our root wrapping Parent component that will wrap any child that will be rendered .
// we can place our Links comppnent inside this root component so that on each screen, we always have the option to navigate to other screens because they will always be rendered along with the child component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* we can place that in more one resuable component called Header */}
        {/* <div>
        <Link href="/">Home</Link>
          <Link href="/performance">Performance</Link>
          <Link href="/reliability">Reliability</Link>
          <Link href="/scale">Scale</Link>

        </div> */}
        {/* we can use our Header component here */}
        <Header/>
        {children}
      </body>
    </html>
  );
}
